pipelines:
  - name: jenkinsPipeline
    steps:
      - name: jenkinsStep1
        type: jenkins
        configuration:
          jenkinsJobName: basic-api
          integrations:
            - name: myJenkinsInt
