resources:
  - name: repo_stepletTestReport1
    type: GitRepo
    configuration:
      gitProvider: v_github
      path: jfbetapipeorg/Org_test_Automation

pipelines:
  - name: v_simple_pipelinetest
    steps:

      - name: bash_testreports1
        type: Bash
        configuration:
          inputResources:
            - name: repo_stepletTestReport1
        execution:
          onExecute:
            - printenv
            - echo "test"
            - cd $res_repo_stepletTestReports_resourcePath
            - python3 -m py_compile tests/core/sampleExecutionFile/calc.py
            - pip install --upgrade pip
            - hash -d pip
            - pip install pytest
            - cd $res_r_stepletTestReports_resourcePath
            - py.test --verbose --junit-xml test-reports/results.xml tests/core/sampleExecutionFile/test_calc.py
            - save_tests $res_repo_stepletTestReports_resourcePath/test-reports/results.xml
#             - echo ${int_varsha_bbs_username}
#             - echo ${int_varsha_bbs_password}
#             - sleep 60m
