resources:
  - name: repo_res1
    type: GitRepo
    configuration:
      gitProvider: v_github
      path: Varsha-Arun/simple
      branches:
        include: tes*
  
pipelines:
  - name: v_simple_pipelinetest
    steps:

      - name: np_cloud_
        type: Bash
        configuration:
          inputResources:
            - name: repo_res1
        execution:
          onExecute:
            - printenv
            - echo "test"
