pipelines:
  - name: v_simple_pipelinetest
    steps:

      - name: triggerStep
        type: Bash
#         configuration:
#           nodePool: np_cloud_u16_ami_043b8e63d0d3809cd
#           integrations:
#             - name: varsha_bbs
        execution:
          onExecute:
            - printenv
            - echo "test"

      - name: step1
        type: Bash
        configuration:
          inputSteps:
            - name: triggerStep
        execution:
          onExecute:
            - printenv
            - echo "test"
                
      - name: step2
        type: Bash
        configuration:
          inputSteps:
            - name: triggerStep
        execution:
          onExecute:
            - printenv
            - echo "test"
            
      - name: step3
        type: Bash
        configuration:
          inputSteps:
            - name: triggerStep
        execution:
          onExecute:
            - printenv
            - echo "test"
            
      - name: step4
        type: Bash
        configuration:
          inputSteps:
            - name: step1
            - name: step2
            - name: step3
        execution:
          onExecute:
            - printenv
            - echo "test"
