pipelines:
  - name: p_np_u18
    steps:

      - name: s_np_u18
        type: Bash
#         configuration:
#           nodePool: np_u16_static
        execution:
          onExecute:
            - printenv
#             - sleep 60m
