pipelines:
  - name: PIPE_5691_0005_test
    steps:
      - name: PIPE_5691_0005_step1_test
        type: Bash
        execution:
          onExecute:
            - echo "going to sleep"
            - sleep 100
            - echo "woke up!"
      - name: PIPE_5691_0005_step2_test
        type: Bash
        configuration:
          inputSteps:
            - name: PIPE_5691_0005_step1_test
        execution:
          onExecute:
            - echo "going to sleep"
            - sleep 100
            - echo "woke up!"
      - name: PIPE_5691_0005_step3_test
        type: Bash
        configuration:
          inputSteps:
            - name: PIPE_5691_0005_step2_test
          requiresApproval:
            timeoutSeconds: 86400
            approvers:
              - secondadmin
            notifications:
              - integrationName: BSAG_4034_SMTP
                recipients:
                  - pipelines.release@gmail.com
                  - email@example.com
              - integrationName: BSAG_4034_SLACK
        execution:
          onExecute:
            - echo "executing step..."
            - sleep 10
