pipelines:
  - name: u16_dy_np
    steps:

      - name: u16_dy_np
        type: Bash
        configuration:
          nodePool: u16_dy_np
        execution:
          onExecute:
            - printenv
            - sleep 60m
