resources:
  - name: repo_demo
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: Varsha-Arun/jpipe

pipelines:
  - name: demoPipelines
    steps:
      - name: demoStep_1
        type: Bash
        configuration: 
          inputResources:
            - name: repo_demo
        execution:
          onExecute:
            - echo "Hello world!!"
            - ./test.sh
