pipelines:
  - name: np_u16_static
    steps:

      - name: np_u16_static
        type: Bash
        configuration:
          nodePool: np_u16_static
        execution:
          onExecute:
            - printenv
            - sleep 60m
