pipelines:
  - name: EnvironmentVariables-008
    configuration:
      environmentVariables:
        readOnly:
          keyEV: 
            default: testValuePipelineReadOnly
            allowCustom: true
    steps:
      - name: S_B_EnvironmentVariables_008
        type: Bash
        configuration:
          environmentVariables:
            keyEV: testValueStep
        execution:
          onExecute:
            - echo $keyEV
            - if [ $keyEV = testValueStep ]; then
                echo "global environment variables values are overidden by step environment variables in step";
              else
                echo "global environment variables values are not overidden by step environment variables in step";
                exit 1;
              fi
