pipelines:
  - name: Matrix_Step_Runtime_Steplet_Rutimetest
    steps:
      - name: matrix_1test
        type: Matrix
        stepletMultipliers:
          environmentVariables:
            - name1: test1
            - name2: test2
            - name3: test3
            - name4: test4
          exclude:
            - environmentVariables:
                name1: test1
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
