resources:
  - name: triggerMatrixRuntime
    type: PropertyBag
    configuration:
      key: value

pipelines:
  - name: lightweightmatrix
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '16'
    steps:
      - name: lightweightStep
        type: Matrix
        configuration:
          multiNode: true
        stepletMultipliers:
          environmentVariables:
            - listOfTests:    "core/steps/Bash/BashGeneric/*.js,\
                              core/steps/Bash/BashIntegrations/*.js,\
                              core/steps/Bash/BashLanguages/*.js,\
                              core/steps/Bash/BashNative/*.js,\
                              core/steps/Bash/BashResources/*.js,\
                              core/resources/Bash/*.js,\
                              core/steps/Bash/BashUtilityFunctions/*.js"
              repositoryFullName:    "jfbetapipeorg/Org_test_Automation_bash"
            - listOfTests:    "core/steps/PowerShell/PSGeneric/Sync/*.js,\
                              core/steps/PowerShell/PSGeneric/Trigger/*.js,\
                              core/steps/PowerShell/PSIntegration/*.js,\
                              core/steps/PowerShell/PSLanguages/*.js,\
                              core/steps/PowerShell/PSNative/*.js,\
                              core/steps/PowerShell/PSResources/*.js,\
                              core/steps/PowerShell/PSUtilityfunctions/*.js"
              repositoryFullName:    "jfbetapipeorg/Org_test_Automation_Powershell"
            - listOfTests:    "core/multibranch/pipelines/*.js,\
                              core/multibranch/resources/*.js,\
                              core/multibranch/pipelineSyncStatuses/*.js"
              repositoryFullName:    "jfbetapipeorg/org_test_automation_MultiBranch"
            - listOfTests: "core/steps/Matrix/*.js"
        execution:
          onExecute:
            - echo Im executing
              

  - name: Matrix_NodePool_Pipeline_Rutime
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '16'
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          multiNode: true
        stepletMultipliers:
          environmentVariables:
            - name: test
          nodePools:
            - win_2019
            - u18dynamic
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
            
  - name: Trigger_Matrix_Tests
    steps:
      - name: trigger
        type: Bash
        configuration:
          outputResources:
            - name: triggerMatrixRuntime
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
            - write_output triggerMatrixRuntime trigger=$run_id
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
        
  - name: Matrix_Step_Type_Host
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          multiNode: true
          inputResources:
            - name: triggerMatrixRuntime
          runtime:
            type: host
        stepletMultipliers:
          environmentVariables:
          - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
        
  - name: Matrix_Step_Type_Image_Custom
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          inputResources:
            - name: triggerMatrixRuntime
          multiNode: true
          runtime:
            type: image
            image:
              custom:
                name: entplus.jfrog.io/devops-docker/jfrog/devops/jfrog-saas-deployer
                tag: latest
                autoPull: true
                options: "--entrypoint=''"
        stepletMultipliers:
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
        
  - name: Matrix_Step_Type_Image_Auto
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          inputResources:
            - name: triggerMatrixRuntime
          multiNode: true
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - '16'
        stepletMultipliers:
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_Step_Steplet_Host
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          inputResources:
            - name: triggerMatrixRuntime
          multiNode: true
        stepletMultipliers:
          runtimes:
            - type: host
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_Step_Steplet_Image_Custom
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          inputResources:
            - name: triggerMatrixRuntime
          multiNode: true
        stepletMultipliers:
          runtimes:
          - type: image
            image:
              custom:
                name: entplus.jfrog.io/devops-docker/jfrog/devops/jfrog-saas-deployer
                tag: latest
                autoPull: true
                options: "--entrypoint=''"
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_Step_Steplet_Image_Auto
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          inputResources:
            - name: triggerMatrixRuntime
          multiNode: true
        stepletMultipliers:
          runtimes:
          - type: image
            image:
              auto:
                language: node
                versions:
                  - '16'
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
        
  - name: Matrix_Step_Runtime_Steplet_Rutime
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          inputResources:
            - name: triggerMatrixRuntime
          multiNode: true
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - '16'
        stepletMultipliers:
          runtimes:
          - type: image
            image:
              auto:
                language: node
                versions:
                  - '17'
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_Pipeline_Rutime_Step_Runtime_Steplet_Rutime
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '15'
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          multiNode: true
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - '16'
        stepletMultipliers:
          runtimes:
          - type: image
            image:
              auto:
                language: java
                versions:
                  - '11'
                  - '13'
          - type: image
            image:
              auto:
                language: node
                versions:
                  - '15'
          environmentVariables:
            - name: test
            - test: hello
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_Multi_Node_Pipeline_Rutime_Step_Runtime
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '15'
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          multiNode: true
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - '16'
        stepletMultipliers:
          environmentVariables:
            - name: test
          nodePools:
            - win_2019
            - u18dynamic
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_NodePool_Pipeline_Rutime_Step_Runtime_Steplet_runtime
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '15'
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          multiNode: true
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                - '17'
        stepletMultipliers:
          runtimes:
            - type: image
              image:
                auto:
                  language: node
                  versions:
                  - '16'
          environmentVariables:
            - name: test
          nodePools:
            - win_2019
            - u18dynamic
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
        
  - name: Matrix_Pipeline_Rutime
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '16'
    steps:
      - name: matrix_1
        type: Matrix
        stepletMultipliers:
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_Pipeline_Rutime_Step_Runtime
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '15'
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                - '16'
        stepletMultipliers:
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
