resources:
  - name: triggerMatrixRuntime
    type: PropertyBag
    configuration:
      key: value
      
pipelines:
  - name: Trigger_Matrix_Tests
    steps:
      - name: trigger
        type: Bash
        configuration:
          outputResources:
            - name: triggerMatrixRuntime
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
            - write_output triggerMatrixRuntime trigger=$run_id
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
  
  - name: Matrix_Step_Type_Host
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          inputResources:
            - name: triggerMatrixRuntime
          runtime:
            type: host
        stepletMultipliers:
          environmentVariables:
          - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
            
  - name: Matrix_Step_Type_Host_multiNode
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          multiNode: true
          inputResources:
            - name: triggerMatrixRuntime
          runtime:
            type: host
        stepletMultipliers:
          environmentVariables:
          - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
        
  - name: Matrix_Step_Type_Image_Custom
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          inputResources:
            - name: triggerMatrixRuntime
          multiNode: true
          runtime:
            type: image
            image:
              custom:
                name: entplus.jfrog.io/devops-docker/jfrog/devops/jfrog-saas-deployer
                tag: latest
                autoPull: true
                options: "--entrypoint=''"
        stepletMultipliers:
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
        
  - name: Matrix_Step_Type_Image_Auto
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          inputResources:
            - name: triggerMatrixRuntime
          multiNode: true
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - '16'
        stepletMultipliers:
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_MultiNode_Steplet_Host
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          inputResources:
            - name: triggerMatrixRuntime
          multiNode: true
        stepletMultipliers:
          runtimes:
            - type: host
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_Step_Steplet_Image_Custom_multiNode
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          inputResources:
            - name: triggerMatrixRuntime
          multiNode: true
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - '16'
        stepletMultipliers:
          runtimes:
            - type: image
              image:
                custom:
                  name: entplus.jfrog.io/devops-docker/jfrog/devops/jfrog-saas-deployer
                  tag: latest
                  autoPull: true
                  options: "--entrypoint=''"
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_MultiNode_Steplet_Image_Auto
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          inputResources:
            - name: triggerMatrixRuntime
          multiNode: true
        stepletMultipliers:
          nodePools:
            - win_2019
            - u18dynamic
          runtimes:
            - type: image
              image:
                auto:
                  language: go
                  versions:
                    - '1.17'
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
        
  - name: Matrix_MultiNode_Step_Runtime_Steplet_Rutime
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          inputResources:
            - name: triggerMatrixRuntime
          multiNode: true
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - '17'
        stepletMultipliers:
          runtimes:
          - type: image
            image:
              auto:
                language: java
                versions: 
                  - '11'
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_Pipeline_Rutime_Step_Runtime_Steplet_Rutime_host
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '15'
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          multiNode: true
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - '16'
        stepletMultipliers:
          runtimes:
            - type: host
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_MultiNode_Pipeline_Rutime_Step_Runtime
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: host
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          multiNode: true
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - '16'
        stepletMultipliers:
          environmentVariables:
            - name: test
          nodePools:
            - win_2019
            - u18dynamic
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_multiNode_Pipeline_Rutime_Step_Runtime_Steplet_runtime
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '15'
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          multiNode: true
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                - '17'
        stepletMultipliers:
          runtimes:
            - type: image
              image:
                auto:
                  language: node
                  versions:
                  - '16'
          environmentVariables:
            - name: test
          nodePools:
            - win_2019
            - u18dynamic
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
  
  - name: Matrix_Pipeline_Rutime_Step_Runtime_Steplet_runtime
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '15'
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          multiNode: true
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                - '17'
        stepletMultipliers:
          runtimes:
            - type: image
              image:
                auto:
                  language: node
                  versions:
                  - '16'
          environmentVariables:
            - name: test
          nodePools:
            - win_2019
            - u18dynamic
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
            
  - name: Matrix_MultiNode_Pipeline_Rutime
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '15'
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          multiNode: true
        stepletMultipliers:
          environmentVariables:
            - name: test
          nodePools:
            - win_2019
            - u18dynamic
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_Pipeline_Rutime
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '16'
    steps:
      - name: matrix_1
        type: Matrix
        stepletMultipliers:
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
          
  - name: Matrix_Pipeline_Rutime_Step_Runtime
    configuration:
      inputResources:
        - name: triggerMatrixRuntime
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '15'
    steps:
      - name: matrix_1
        type: Matrix
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                - '16'
        stepletMultipliers:
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
