pipelines:
  - name: Matrix_NodePool_Pipeline_Rutime_Test
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '16'
    steps:
      - name: matrix_1test
        type: Matrix
        configuration:
          multiNode: true
        stepletMultipliers:
          environmentVariables:
            - name: test
              name2: test2
            - type: step
              type2: step2
          nodePools:
            - win_2019
            - u18dynamic
            - testu18
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
            
  - name: Trigger_Matrix_Tests_1
    steps:
      - name: trigger_mat
        type: Matrix
        stepletMultipliers:
          environmentVariables:
            - name: test
              name2: test2
            - type: step
              type2: step2
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
            - write_output triggerMatrixRuntime trigger=$run_id
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
        
  - name: Matrix_Step_Type_Host_2
    steps:
      - name: matrix_1io
        type: Matrix
        configuration:
          multiNode: true
          runtime:
            type: host
        stepletMultipliers:
          environmentVariables:
            - name: test
            - test1: env1
            - test2: env2
          nodePools:
            - win_2019
            - u18dynamic
            - testu18
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'

  - name: Matrix_nodepool_and_env
    steps:
      - name: matrix_1io
        type: Matrix
        configuration:
          multiNode: true
#           runtime:
#             type: host
        stepletMultipliers:
          environmentVariables:
            - name: test
            - test1: env1
            - test2: env2
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
