pipelines:
  - name: Matrix_NodePool_Pipeline_Rutime_Varsha
    configuration:
      nodePool: windows
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '16'
    steps:
      - name: matrix_1_Varsha
        type: Matrix
        stepletMultipliers:
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
                
  - name: Matrix_Pipeline_Rutime_Step_Runtime_Varsha
    steps:
      - name: matrix_1_Varsha
        type: Matrix
        configuration:
          multiNode: true
        stepletMultipliers:
          runtimes:
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - '17'
          nodePools:
            - pool
            - windows
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
                           
  - name: Matrix_Pipeline_Rutime_Steplet_Runtime_Varsha
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - '16'
    steps:
      - name: matrix_1_Varsha
        type: Matrix
        configuration:
          multiNode: true
        stepletMultipliers:
          nodePools:
            - pool
            - windows
          environmentVariables:
            - name: test
        execution:
          onExecute:
            - echo Im executing
          onSuccess:
            - echo 'i am onsuccess'
          onFailure:
            - echo 'i am onfailure'
          onComplete:
            - echo 'i am oncomplete'
