resources:
  - name: r_stepTestReports
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: Varsha-Arun/simple

pipelines:
  - name: P_stepTestReports
    configuration:
      environmentVariables:
        readOnly:
          TEST_ENV: "pipelines"
          JUST_FES: "options"
          LOL_FOO: "test"
    steps:
      - name: s_stepTestReports
        type: Bash
        configuration:
          environmentVariables:
            key1: "value1"
            key2: "value2"
            key3: "value3"
          inputResources:
            - name: r_stepTestReports
        execution:
          onExecute:
            - printenv
            - set_run_name 'test_run_name_too_long_test_run_name_too_long_test_run_name_too_long_test_run_name_too_long_test_run_name_too_long_test_run_name_too_long_'
            - update_run_description 'test_run_description_too_long_test_run_description_too_long_test_run_description_too_long_test_run_description_too_long_test_run_description_too_long_test_run_description_too_long_test_run_description_too_long_'’
            - cd $res_r_stepTestReports_resourcePath
            - python3 -m py_compile tests/core/sampleExecutionFile/calc.py
            - pip install --upgrade pip
            - hash -d pip
            - pip install pytest
            - cd $res_r_stepTestReports_resourcePath
            - py.test --verbose --junit-xml test-reports/results.xml tests/core/sampleExecutionFile/test_calc.py
            - save_tests $res_r_stepTestReports_resourcePath/test-reports/results.xml

