pipelines:
  - name: P_WF_pipelines
    configuration:
      integrations:
        - name: auto_ssh
      environmentVariables:
        readOnly:
          IP_ADDRESS: 
            allowCustom: true
            default: "100.10.140.189"
          User: "varshaa"
    steps:
      - name: P_WF_step1
        type: Bash
        configuration:
          inputResources:
            - name: r_WF_gr
          outputResources:
            - name: pb_branchSnapshot_version
        execution:
          onExecute:
            - echo $IPAddress
            - pushd $res_r_testsimplerepo_resourcePath
            - scp -i ${int_auto_ssh_privateKey} installJenkins.sh $IP_ADDRESS:/home/$User
            - ssh -i ${int_auto_ssh_privateKey} $IP_ADDRESS "cd /home/$User; ./installJenkins.sh"
            - api_token=090909090909090900900
            - write_output pb_branchSnapshot_version api_token=$run_number
      
resources:
  - name: r_WF_gr
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: Varsha-Arun/simple
      branches:
        include: master
        
  - name: pb_branchSnapshot_version
    type: PropertyBag
    configuration:
      api_token: ""
      


