pipelines:
  - name: P_WF_pipelines
    configuration:
      integrations:
        - name: test_ssh
        - name: varsha_github
      environmentVariables:
        readOnly:
          IP_ADDRESS: 
            allowCustom: true
            default: "100.10.164.231"
          User: "ubuntu"
          SSH_PRIVATE_KEY:
            allowCustom: false
            default:  "${int_test_ssh_privateKey}"
            description: "SSH private key value in automation"
    steps:
      - name: P_WF_step1
        type: Bash
        configuration:
          inputResources:
            - name: r_WF_gr
          outputResources:
            - name: pb_branchSnapshot_version
        execution:
          onExecute:
            - echo $IP_ADDRESS
            - echo $User
#             - echo ${int_auto_ssh_privateKey}
#             - echo ${int_varsha_github_token}
#             - echo $SSH_PRIVATE_KEY
#             - echo ${int_auto_ssh_publicKey}
            - pushd $res_r_WF_gr_resourcePath
            - touch /tmp/pem_key.pem
            - echo ${int_test_ssh_privateKey} | sed 's/- /-\n/g; s/ -/\n-/g' | sed '/KEY/! s/ /\n/g'> /tmp/pem_key.pem
            - cat /tmp/pem_key.pem
            - ls -la
            - ls -la /tmp
            - cat /tmp/pem_key.pem
            - cat installJenkins.sh
            - chmod 400 /tmp/pem_key.pem
            - scp -i /tmp/pem_key.pem installJenkins.sh ubuntu@$IP_ADDRESS:/home/ubuntu
#             - ssh -i pem_file_path $IP_ADDRESS "cd /home/$User; ./installJenkins.sh"
#             - api_token=090909090909090900900
#             - write_output pb_branchSnapshot_version api_token=$run_number

#   - name: test_app
#     type: Jenkins
#     configuration:
#       inputSteps:
#         - name: p1_s2
#       jenkinsJobName: testFolder/pipetest
#       integrations:
#         - name: int_jenkins2
#       outputResources:
#         - name: myPropertyBag
        
resources:
  - name: r_WF_gr
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: Varsha-Arun/simple
      branches:
        include: master
        
  - name: pb_branchSnapshot_version
    type: PropertyBag
    configuration:
      api_token: ""
      


