pipelines:
  - name: pipeline1
    steps:
      - name: testmatrix
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables: 
            - env1: one 
            - env2: two
        execution:
          onExecute:
            - echo lol
