resources:
  - name: P_WF_5933_004_resource
    type: PropertyBag
    configuration:
      test: test
      
  - name: all_gr
    type: GitRepo
    configuration:
      path: Varsha-Arun/pipelines
      gitProvider: varsha_github
        
pipelines:
  - name: pipeline_P_WF_5933_004
    configuration:
      environmentVariables:
        readOnly:
          env1:     value1
          env2:     value2
      integrations:
        - name: s_artifactory
    steps:
      - name: P_WF_5933_004_1
        type: Bash
        configuration:
          inputResources:
            - name: P_WF_5933_004_resource
            - name: all_gr
          environmentVaribales:
            - foo: bar
            - test1: step1
        execution:
          onExecute:
            - echo "executing step..."
      - name: P_WF_5933_004_2
        type: Bash
        configuration:
          integrations:
            - name: s_artifactory
          inputResources:
            - name: P_WF_5933_004_resource
          inputSteps:
            - name: P_WF_5933_004_1
        execution:
          onExecute:
            - echo "executing step..."
