pipelines:
  - name: pipeline1
    steps:
      - name: step1
        type: MATRIX
        stepMode: BASH
        stepletMultipliers:
          environmentVariables: 
            - env1: one 
            - env2: two
        execution:
          onExecute:
            - echo lol
