pipelines:
  - name: pipeline1
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo lol

      - name: step2
        type: Bash
        configuration:
          inputSteps:
            - name: step1
          requiresApproval:
            approvers:
              - admin
        execution:
          onExecute:
            - echo lol
