pipelines:
  - name: P_WF_pipelines
    configuration:
      integrations:
        - name: auto_ssh
      environmentVariables:
        readOnly:
          IP_ADDRESS: 
            allowCustom: true
            default: "100.10.158.24"
          User: "varshaa"
    steps:
      - name: P_WF_step1
        type: Bash
        configuration:
          inputResources:
            - name: r_WF_gr
          outputResources:
            - name: pb_branchSnapshot_version
        execution:
          onExecute:
            - echo $IP_ADDRESS
            - echo ${int_auto_ssh_privateKey}
            - echo ${int_auto_ssh_publicKey}
            - pushd $res_r_WF_gr_resourcePath
            - touch /tmp/pem_key
            - echo -e ${int_auto_ssh_privateKey} > /tmp/pem_key
            - ls -la
            - cat /tmp/pem_key
            - cat installJenkins.sh
            - chmod 600 /tmp/pem_key
            - scp -i /tmp/pem_key -o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=0 -P 22 installJenkins.sh $IP_ADDRESS:/home/$User
#             - ssh -i pem_file_path $IP_ADDRESS "cd /home/$User; ./installJenkins.sh"
#             - api_token=090909090909090900900
#             - write_output pb_branchSnapshot_version api_token=$run_number
      
resources:
  - name: r_WF_gr
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: Varsha-Arun/simple
      branches:
        include: master
        
  - name: pb_branchSnapshot_version
    type: PropertyBag
    configuration:
      api_token: ""
      


