pipelines:
  - name: priorityAndAffinityGroupsPipeline
    steps:

      - name: pag_step_001
        type: Bash
        execution:
          onExecute:
            - echo "step 1 is running"

      - name: pag_step_004
        type: Bash
        configuration:
          environmentVariables:
            pag_step_004: "yes"
            key1: "value1"
            key2: "value2"
            key3: "value3"
            test_step: "test space"
          inputSteps:
            - name: pag_step_001
          affinityGroup: ag_group1
          priority: 4
        execution:
          onExecute:
            - echo "step 2 is running"
            - if [ "$pag_step_004" != "yes" ]; then return 1; fi
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"   
            - printenv

      - name: pag_step_002
        type: Bash
        configuration:
          environmentVariables:
            pag_step_002: "yes"
          inputSteps:
            - name: pag_step_001
          affinityGroup: ag_group1
          priority: 1
        execution:
          onExecute:
            - echo "step 3 is running"
            - printenv
            - if [ "$pag_step_002" != "yes" ]; then return 1; fi
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"   

      - name: pag_step_003
        type: Bash
        configuration:
          environmentVariables:
            pag_step_003: "yes"
          inputSteps:
            - name: pag_step_001
          affinityGroup: ag_group1
          priority: 3
        execution:
          onExecute:
            - echo "step 4 is running"
            - printenv
            - if [ "$pag_step_003" != "yes" ]; then return 1; fi
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"   

      - name: pag_step_006
        type: Bash
        configuration:
          environmentVariables:
            pag_step_006: "yes"
          inputSteps:
            - name: pag_step_002
            - name: pag_step_003
            - name: pag_step_004
          affinityGroup: ag_group1
          priority: 2
        execution:
          onExecute:
            - echo "step 5 is running"
            - printenv
            - if [ "$pag_step_006" != "yes" ]; then return 1; fi
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"   

      - name: pag_step_005
        type: Bash
        configuration:
          environmentVariables:
            pag_step_005: "yes"
          inputSteps:
            - name: pag_step_002
            - name: pag_step_003
            - name: pag_step_004
          affinityGroup: ag_group1
          priority: 1
        execution:
          onExecute:
            - echo "step 6 is running"
            - printenv
            - if [ "$pag_step_005" != "yes" ]; then return 1; fi
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"   

      - name: pag_step_007
        type: Bash
        configuration:
          environmentVariables:
            pag_step_007: "yes"
          inputSteps:
            - name: pag_step_005
            - name: pag_step_006
          affinityGroup: ag_group1
          priority: 2
        execution:
          onExecute:
            - echo "step 7 is running"
            - printenv
            - if [ "$pag_step_007" != "yes" ]; then return 1; fi
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"   
