pipelines:
  - name: pipelineRunState
    steps:
      - name: step1test
        type: Bash
        execution:
          onExecute:
            - echo "executing step..."
            - sleep 10
            - exit 1

  
      - name: step2test
        type: Bash
        configuration:
          inputSteps:
            - name: step1test
              status:
                - success
        execution:
          onExecute:
            - echo "executing step..."
            - sleep 10
            
      - name: step3test
        type: Bash
        configuration:
          outputResources:
            - name: runStatusResource
          inputSteps:
            - name: step2test
        execution:
          onExecute:
            - echo "executing step..."
            - sleep 10
#             - exit 1
            
      - name: step4test
        type: Bash
        configuration:
          inputResources:
            - name: runStatusResource
              newVersionOnly: true

#           inputSteps:
#             - name: step2test
#               status:
#                 - success
        execution:
          onExecute:
            - echo "executing step..."
            - sleep 10
resources:
  - name: runStatusResource
    type: PropertyBag
    configuration:
      test: test
