

pipelines:

  - name: pipelineConditionalVariabletest
    steps:
      - name: step1cvtest
        type: Bash
        execution:
          onExecute:
            - echo "executing step..."
            - add_run_variables "key=1"

      - name: step2cvtest
        type: Bash
        configuration:
          condition: 'key = "1"'
          inputSteps:
            - name: step1cvtest
        execution:
          onExecute:
            - echo "executing step..."
            - echo $key
            - sleep 10
